###############################################################
# For Vim
###############################################################

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
if = "!has('nvim')"
depends = ['asyncomplete-lsp.vim', 'asyncomplete-buffer.vim']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

###############################################################
# For NeoVim
###############################################################

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim') && g:dot_deoplete"
build = ':UpdateRemotePlugins'
depends = ['ultisnips']
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
hook_source = 'source ~/.vim/rc/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
depends = ['vim-snippets']
hook_add = '''
    let g:UltiSnipsExpandTrigger="<c-k>"
    let g:UltiSnipsJumpForwardTrigger="<c-k>"
    let g:UltiSnipsJumpBackwardTrigger="<c-b>"
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/neco-vim'
if = "has('nvim')"
on_ft = ['vim']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'ujihisa/neco-look'
if = "has('nvim')"
on_ft = ['gitcommit', 'markdown']
depends = ['deoplete.nvim']
