[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'SirVer/ultisnips'
depend = ['vim-snippets']
hook_add = '''
    let g:UltiSnipsExpandTrigger="<c-k>"
    let g:UltiSnipsJumpForwardTrigger="<c-k>"
    let g:UltiSnipsJumpBackwardTrigger="<c-b>"
'''

[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
depend = ['vim-snippets']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = 'source ~/.vim/rc/plugins/nvim-cmp.rc.vim'
