[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'go']
depends = ['async.vim']
hook_source = '''
source ~/.vim/rc/plugins/lsp.rc.vim
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_ft = ['python', 'go']
