[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depend = [
    'cmp-nvim-lsp',
    'cmp-buffer',
    'cmp-path',
    'cmp-spell',
    'cmp-nvim-lsp-signature-help',
    'cmp-nvim-ultisnips',
]
on_event = 'InsertEnter'
hook_source = 'luafile ~/.vim/rc/plugins/nvim-cmp.rc.lua'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_event = 'InsertEnter'

[[plugins]]
repo = 'f3fora/cmp-spell'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_event = 'InsertEnter'

[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
on_event = 'InsertEnter'
depend = ['ultisnips']

[[plugins]]
repo = 'SirVer/ultisnips'
on_event = 'InsertEnter'
depend = ['vim-snippets']
hook_source = '''
    let g:UltiSnipsExpandTrigger="<c-k>"
    let g:UltiSnipsJumpForwardTrigger="<c-k>"
    let g:UltiSnipsJumpBackwardTrigger="<c-b>"
'''

[[plugins]]
on_event = 'InsertEnter'
repo = 'honza/vim-snippets'
