[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = [
    'vim-lsp-settings',
    'vista.vim'
]
on_ft = [
    'sql',
    'go',
    'typescript',
    'typescriptreact',
    'javascript',
    'javascriptreact',
    'vue',
    'markdown',
]
hook_add = '''
    source ~/.vim/rc/plugins/lsp.rc.vim
'''

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'lighttiger2505/sqls.vim'
on_ft = ['sql']
hook_add = '''
    augroup SqlsCommands
        autocmd!
        autocmd FileType sql nmap <silent><LocalLeader>rr <Plug>(sqls-execute-query)
        autocmd FileType sql vmap <silent><LocalLeader>rr <Plug>(sqls-execute-query)
        autocmd FileType sql nmap <silent><LocalLeader>rv <Plug>(sqls-execute-query-vertical)
        autocmd FileType sql vmap <silent><LocalLeader>rv <Plug>(sqls-execute-query-vertical)
        autocmd FileType sql nmap <silent><LocalLeader>sd <Plug>(sqls-switch-database)
        autocmd FileType sql nmap <silent><LocalLeader>sc <Plug>(sqls-switch-connection)
    augroup END
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista']
hook_add = '''
    nnoremap <silent> <Leader>o :<C-u>Vista!!<CR>
    let g:vista_sidebar_width = 40
    let g:vista_echo_cursor = 0
    " let g:vista_executive_for = {
    "   \ 'go': 'lcn',
    "   \ 'python': 'lcn',
    "   \ }
'''
