[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depend = [
    'cmp-nvim-lsp',
    'cmp-buffer',
    'cmp-path',
    'cmp-spell',
    'cmp-nvim-lsp-signature-help',
]
on_event = 'InsertEnter'
hook_source = 'luafile ~/.vim/rc/plugins/nvim-cmp.rc.lua'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_event = 'InsertEnter'

[[plugins]]
repo = 'f3fora/cmp-spell'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_event = 'InsertEnter'

[[plugins]]
on_event = 'InsertEnter'
repo = 'honza/vim-snippets'
