[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# if = "!has('nvim')"
on_ft = ['python', 'go', 'typescript', 'c', 'cpp']
depends = ['async.vim', 'deoplete-vim-lsp', 'vista.vim']
hook_source = '''
    source ~/.vim/rc/plugins/lsp.rc.vim
'''

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = 'deoplete.nvim'
hook_source = '''
    let g:deoplete#sources#vim_lsp#show_info = 1
'''

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# if = "has('nvim')"
# build = 'install.sh'
# on_ft = ['go', 'python']
# hook_source = 'source ~/.vim/rc/plugins/neolsp.rc.vim'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# on_ft = ['go', 'python']
# build = 'coc#util#install()'
# hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'
