#!/bin/zsh

if [[ $1 = "ssh" ]]; then
  pane_pid=$2
  info=$({ pgrep -flaP $pane_pid ; ps -o command -p $pane_pid; } | xargs -I{} echo {} | awk '/ssh/' | sed -E 's/^[0-9]*[[:blank:]]*ssh //')
  port=$(echo $info | grep -Eo '\-p ([0-9]+)'|sed 's/-p //')
  if [ -z $port ]; then
    local port=22
  fi
  info=$(echo $info | sed 's/\-p '"$port"'//g')
  user=$(echo $info | awk '{print $NF}' | cut -f1 -d@)
  host=$(echo $info | awk '{print $NF}' | cut -f2 -d@)

  if [ $user = $host ]; then
    user=$(whoami)
    list=$(awk '
      $1 == "Host" {
        gsub("\\\\.", "\\\\.", $2);
        gsub("\\\\*", ".*", $2);
        host = $2;
        next;
      }
      $1 == "User" {
      $1 = "";
        sub( /^[[:space:]]*/, "" );
        printf "%s|%s\n", host, $0;
      }' ~/.ssh/config
    )
    echo $list | while read line; do
      host_user=${line#*|}
      if [[ "$host" =~ $line ]]; then
        user=$host_user
        break
      fi
    done
  fi
  ssh_hostname=" ssh:$user@$host "
  git_info=""
  directory=""
else
  if git_status=$(cd $3 && git status 2>/dev/null ); then
    git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
    case $git_status in
      *Changes\ not\ staged* ) state="#[bg=colour013,fg=black] ± #[fg=default]" ;;
      *Changes\ to\ be\ committed* ) state="#[bg=blue,fg=black] + #[default]" ;; 
      * ) state="#[bg=green,fg=black] ✔ #[default]" ;;
    esac
    if [[ $git_branch = "master" ]]; then
      git_info="#[underscore]#[bg=black,fg=blue] ⭠ ${git_branch} #[default]${state}"
    else
      git_info="#[underscore]#[bg=black,fg=colour014] ⭠ ${git_branch} #[default]${state}"
    fi
  else
    git_info=""
  fi
  ssh_hostname=""
  directory="$3"
fi

echo "#[bg=colour013,fg=black]$ssh_hostname#[default]#[bg=black,fg=cyan]#[underscore]$directory#[default]$git_info"
