source-file ~/.config/tmux/conf.d/base.tmux
source-file ~/.config/tmux/conf.d/keybind.tmux
source-file ~/.config/tmux/conf.d/copy.tmux
source-file ~/.config/tmux/conf.d/popup.tmux
source-file ~/.config/tmux/conf.d/colorschema.tmux
source-file ~/.config/tmux/conf.d/statusline.tmux

# keep this line at the very bottom of tmux.conf
source-file ~/.config/tmux/conf.d/tpm.tmux
