gui:
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: 'C'
    context: 'global'
    command: "git commit"
    subprocess: true
    description: '(custom) git commit on my favorite editor'
