prSections:
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me -label:dependencies 
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 40
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs:
    - key: D
      command: |-
        tmux new-window -c {{.RepoPath}} '
          tmux rename-window {{.RepoName}}#{{.PrNumber}}
          local branch=$(gh pr status --json baseRefName -q '.currentBranch.baseRefName')
          git fetch origin ${branch}:${branch}
          gh pr checkout {{.PrNumber}}
          gh pr view --web  {{.PrNumber}}
          nvim -c ":DiffviewOpen origin/${branch}...{{.HeadRefName}}"
        '
repoPaths:
  MobilityTechnologies/*: ~/dev/src/github.com/MobilityTechnologies/*
  MobilityTechnologies/kingston: ~/dev/src/github.com/MobilityTechnologies/kingston_review
  MobilityTechnologies/kingston-static: ~/dev/src/github.com/MobilityTechnologies/kingston-static_review
  key: d
theme:
  ui:
    table:
      showSeparator: false
pager:
  diff: ""
