[env]
GOBIN  = "{{env.HOME}}/go/bin"

[settings]
experimental = true
go_set_gobin = false
install_before = "7d"
idiomatic_version_file_enable_tools = ["node"]

[tools]
# Golang
go = "1.26.2"
golangci-lint = "2.11.4"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/lighttiger2505/liary" = "latest"
"go:github.com/lighttiger2505/mcm" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
# Node.js
node = "25"
"npm:biome" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:jsonlint" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:ccusage" = "latest"
"npm:@marp-team/marp-cli" = "latest"
# Python
python = "latest"
uv = "latest"
"pipx:mycli" = "latest"
"pipx:pgcli" = "latest"
# CLI commands
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:cli/cli" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:max-sixty/worktrunk" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:x-motemen/ghq" = "latest"
# "github:eza-community/eza" = "latest"
# "github:jonas/tig" = "latest"
# "github:rtk-ai/rtk" = "latest"
# "github:tmux/tmux" = "latest"
