[env]
GOBIN  = "{{env.HOME}}/go/bin"

[settings]
experimental = true
go_set_gobin = false
install_before = "7d"
trusted_config_paths = [
"~/src/github.com/MobilityTechnologies",
]
idiomatic_version_file_enable_tools = ["node"]

[tools]
# Golang
go = "1.26.2"
golangci-lint = "2.11.4"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/lighttiger2505/liary" = "latest"
"go:github.com/lighttiger2505/mcm" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
# Node.js
node = "25"
"npm:biome" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:jsonlint" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:ccusage" = "latest"
"npm:@antfu/ni" = "latest"
# Python
python = "latest"
uv = "latest"
"pipx:mycli" = "latest"
"pipx:pgcli" = "latest"
# CLI commands
"github:jonas/tig" =  "latest"
"github:tmux/tmux" =  "latest"
"aqua:jqlang/jq" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:x-motemen/ghq" = "latest"
